version: '3.5'
services:

  django:
    container_name: "django_backend"
    restart:  on-failure
    depends_on:
      - postgres

    env_file:
      - .env

    build:
      context: ./django_service
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      trans_net:
        ipv4_address: 192.130.0.3

    volumes:
      - ./django_service/FrontApp:/app/FrontApp


  postgres:
    container_name: "postgres_db"
    image: postgres:alpine3.18
    restart:  always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgres/data
#    ports: DO_NOT_REMOVE -> Pour exposition public (potentiel)
#      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgres/data
    networks:
      trans_net:
        ipv4_address: 192.130.0.2

networks:
  trans_net:
    name: trans_net
    driver: bridge
    ipam:
      config:
        - subnet: 192.130.0.0/16
          gateway: 192.130.0.1

volumes:
  postgres_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./postgres/volume/data
