version: '3'
services:
  hello_world:
    container_name: "alex_hello_world"
    #env_file: .env
    #restart:  always
    build: 
      context: ./Hello_world
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
#    volumes:
#      - ./requirements/wordpress/volume/:/var/www
