version: '3.5'
services:
  nestjs:
    container_name: "nestjs_backend"
    restart:  on-failure
    depends_on:
      - postgres

    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: psql
      DB_PASSWORD: ReMoVeMeFrOmHeRe
      DB_NAME: nestdb
      DATABASE_URL: "postgresql://psql:ReMoVeMeFrOmHeRe@localhost:5432/nestdb?schema=public"

    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - trans_net
    volumes:
      - ./backend/src:/app/src


  postgres:
    container_name: "postgres_db"
    image: postgres:alpine3.18
    restart:  always
    environment:
      - POSTGRES_USER=psql
      - POSTGRES_PASSWORD=ReMoVeMeFrOmHeRe
      - POSTGRES_DB=nestdb
      - PGDATA=/var/lib/postgres/data

    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgres/data
    networks:
      - trans_net

  angular:
    container_name: "angular_frontend"
    # env_file: .env
    restart:  on-failure
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    networks:
      - trans_net
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/dist:/app/dist

  # react:
  #   container_name: "react_frontend"
  #   # env_file: .env
  #   #restart:  on-failure
  #   build: 
  #     context: ./frontend_react
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "5173:5173"
  #   networks:
  #     - trans_net
  #   volumes:
  #     - ./frontend_react/frontend_vite_react/src:/app/frontend_vite_react/src
  #     - ./frontend_react/frontend_vite_react/dist:/app/frontend_vite_react/dist


networks:
  trans_net:
    name: trans_net
    driver: bridge

volumes:
  postgres_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./postgres/data
      #device: ./postgres/postgres_volume


  # wordpress:
  #   container_name: "wordpress_inception"
  #   env_file: .env
  #   restart:  on-failure
  #   build:
  #     context: ./requirements/wordpress
  #     dockerfile: ./Dockerfile
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - inception
  #   volumes:
  #     - wordpress_vlm:/var/www/html

  # mariadb:
  #   container_name: "mariadb_inception"
  #   env_file: .env
  #   restart:  on-failure
  #   build:
  #     context: ./requirements/mariadb
  #     dockerfile: ./Dockerfile
  #   networks:
  #     - inception
  #   volumes:
  #     - mariadb_vlm:/var/lib/mysql

